### ISSUE TITLE
Suppport for plugins

### ISSUE THREAD

**Issue by mrfatstrat** [Diabol/scrolls#6]
As a user I want to be able to be able to write cusotm adapters that plugs into the scrolls report and templateing engine so that I can customize the tool for my needs without forking the project

**Comment by RobertDahlstrom** [comment]
Closing as this can be considered done. Perhaps reopen one for output plugins, although it can be achieved by replacing the default HTML templates.

**Comment by marcusphi** [comment]
I don't know what is the level of the project, but I think that
1) the template language/framework (remarker, velocity, etc) should be pluggable
2) An output format that we used at comhem, which I think was a good idea, was Jira markup. Is that possible today with Scrolls?

**Comment by RobertDahlstrom** [comment]
1) Currently not supported, it's FreeMarker all the way (but it would be interesting exercise to make it pluggable). You can, however, replace the HTML templates with say, XML templates if you want already.

2) In theory, by defining FreeMarker templates for it. Although Scrolls is a bit tailored for HTML right now.
